sonar.projectKey=reports-IT-support-project
sonar.projectName=Reports IT Support Project
sonar.organization=arieloou
sonar.sources=src
sonar.language=py
sonar.python.version=3.14.3
sonar.sourceEncoding=UTF-8