on: 
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches: [main, develop]
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

name: SonarQube-Cloud
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0 
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 